function addTwo(num: number) {
    return num + 2;
}

addTwo(5)


const err = (err: string): string => {
    return `erro Ã© ${err}`
}